### ISSUE TITLE
Add functionality to Available Inventory Report - 5 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#10]
**Problem:**
As a user, I need the ability to print a list of the available inventory in the bookstore.

**Acceptance Criteria:**
- A screen should be available that is dedicated to the Available Inventory report
- Filters should be available to filter by availability, author and genre
- There should be a preview section that will display results
- There should be a print button to print results.

**Task List:**

- [x] Create Available Inventory Report Screen https://github.com/mbasso29/BestofBooks/issues/35
- [x] Create filters to filter report search https://github.com/mbasso29/BestofBooks/issues/36
- [x] Create Search button https://github.com/mbasso29/BestofBooks/issues/37
- [x] Provide preview section to review report results https://github.com/mbasso29/BestofBooks/issues/38
- [x] Add print button https://github.com/mbasso29/BestofBooks/issues/39

**Comment by mbasso29** [comment]
Adding 8 points to this story due to complexity
