### ISSUE TITLE
Create Search Tab - 7 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#15]
- [x] Create Search Screen https://github.com/mbasso29/BestofBooks/milestone/23
- [x] Add drop down field https://github.com/mbasso29/BestofBooks/issues/41
- [x] Add text field https://github.com/mbasso29/BestofBooks/issues/42
- [x] Add Search Button https://github.com/mbasso29/BestofBooks/issues/43
- [x] Add Clear Button https://github.com/mbasso29/BestofBooks/issues/44
- [x] Add preview section https://github.com/mbasso29/BestofBooks/issues/46
- [x] Pull results from the stored procedure on Search click https://github.com/mbasso29/BestofBooks/issues/45
- [x] Clear search text when Search button is clicked. https://github.com/mbasso29/BestofBooks/issues/47
