### ISSUE TITLE
Set functionality of trash can to set qty to 0 - 4 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#19]
**Problem:**
As a user, I need the ability to set the qty of a book to 0 when we no longer have that book in stock

**Acceptance Criteria:**
- Trash can should display next to each line item
- Selecting the trash can will set Qty to 0 in the database
- Setting Qty to 0 will set In Stock to false
- Setting In Stock to false will remove the item from the view only Inventory list

**Task List:**
- [x] Add trash can to each line item
- [ ] Add functionality to set qty to 0 of the line item when the trask can is clicked
- [ ] Set In stock to false when Qty = 0
- [ ] Remove item from available inventory view list when in stock is false

**Comment by mbasso29** [comment]
Does not add anything to the app, pulling from app to do
