### ISSUE TITLE
Add qty column in Inventory List table - 1 point

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#20]
**Problem:**
As a user, I need the ability to see how many books are in stock per book

**Acceptance Criteria:**
- Add qty column on Inventory List table
- Tie qty column to the qty column in database

**Task List:**
- [x] Add qty column
- [x] Set field size to 3
- [x] Set qty column to equal qty column in database
