### ISSUE TITLE
Add price to database and corresponding UI tables - 2 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#24]
**Problem:**
As a user, I need the ability to see the price per book on the inventory list

**Acceptance Criteria:**
- Add price column to inventory list table
- Add price column to book table in database
- Set field to only allow 5 characters

**Task List:**
- [x] Add price column in UI
- [x] Add price column in database
- [x] Set field to only allow 5 characters
