### ISSUE TITLE
Add Inventory List Report - 3 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#34]
**Problem:**
As a user, I need the ability to navigate to the reports screen and see an option for an Available Inventory List Report

**Acceptance Criteria:**

- Report will show as a link on the reports screen
- Selecting the link will bring the user to a new screen that will hold the filters for the Available Inventory List Report

**Task List:**
- [x] Add a hyperlink to the reports screen page
- [x] Ensure hyperlink and other text is centered on the page
- [x] Ensure hyperlink will bring user to another page called Available Inventory List Report

**Comment by Super-Derek** [comment]
View/page created for AvailableInventoryListReport with link added to Reports page
