### ISSUE TITLE
Create filters to filter Available Inventory Report - 4 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#36]
**Problem:**
As a user, I need the ability to filter the inventory list by author, genre and whether the item is in stock.

**Acceptance Criteria:**
- Filters should include two drop-downs for author and genre
- Filters should also include a checkbox for in-stock
- None of these options will be required
- By default, In Stock should be selected

**Task List:**
- [x] Add drop-downs for author and genre
- [x] Each drop-down should include the available options from the database
- [x] Add checkbox for In stock
- [x] Set "In Stock" to be checked

**Comment by Super-Derek** [comment]
In Stock was changed to Dropdown Select instead of checkbox and includes options for all, in-stock, not in-stock.
