### ISSUE TITLE
Add a drop down field for the Search screen - 3 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#41]
**Problem:**
As a user, I need the ability to filter the Inventory List down by a certain criteria

**Acceptance criteria:**
- create a drop-down option on the Search screen
- center this drop-down and style according to the existing color scheme (see the Create Account screen for an idea)
- drop-down should include options of title, author last name, author first name, and genre

**Task List:**
- [x] Add drop-down field
- [x] Style field according to existing scheme
- [x] Include title, author last name, author first name, and genre for options
