### ISSUE TITLE
Add text field to Search screen - 3 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#42]
**Problem:**
As a user, I need the ability to filter the Inventory List down by certain criteria

**Acceptance criteria:**
- create a text box on the Search screen
- center this text box and style according to the existing color scheme (see the Create Account screen for an idea)
- text box should allow up to 25 characters

**Task List:**
- [x] Add text box field
- [x] Style field according to existing scheme
- [x] Set character limit to 25 characters
