### ISSUE TITLE
Add clear button to search tab - 3 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#44]
**Problem:**
As a user, I need the ability to clear the filters I selected

**Acceptance criteria:**
- create a clear button on the Search screen
- button should be centered on the screen and match existing color scheme
- button should appear next to the search button

**Task List:**
- [x] Add clear button
- [x] Style field according to existing scheme
- [x] Clicking the Clear button will clear the drop-down and text fields
