### ISSUE TITLE
Add filters to Change History Report - 4 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#48]
**Problem:**
As a user, I need the ability to filter the change history by username, user last name, and date.

**Acceptance Criteria:**
- Filters should include drop-downs for username and user last name
- Filters should also include a date picker for date
- The date field should be required

**Task List:**
- [x] Add drop-downs for username and user last name
- [x] Each drop-down should include the available options from the database
- [x] Add date picker
- [x] Require date to be selected to search
