### ISSUE TITLE
Add audit table to database - 3 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#49]
**Problem:**
As a developer, I need the ability to audit the database for any modifications

**Acceptance criteria:**
- create a new table for the audit
- ensure appropriate audit columns are added and ensure modified by username and dates are included
- ensure all changes made to the database produce an audit log

**Task List:**
- [x] Add audit table
- [x] Add audit logging
- [x] Test that changes made write to audit table

**Comment by Super-Derek** [comment]
Audit table has been built and added to DB, but still working on way to include User Last Name as property
