### ISSUE TITLE
Add stored procedure that will accept date, username and user last name - 4 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#50]
**Problem:**
As a developer, I need the ability to pull search results based on filters selected in the UI from the database

**Acceptance criteria:**
- create a stored procedure in the database
- stored procedure should accept parameters for date, username, and user last name
- the date parameter will be required to run stored procedure
- information from the stored procedure should be pulled when selecting the Search button on the Change History report screen
- Results will be displayed in a preview screen underneath the search and clear buttons

**Task List:**
- [x] Add stored procedure
- [x] Set stored procedure to accept parameters: date AND username OR user last name OR none
- [x] run stored procedure when Search button is clicked
- [x] display results in preview section on the Change History report
