### ISSUE TITLE
Add print button to Change History report - 3 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#51]
**Problem:**
As a user, I need the ability to print the report after the Search button is clicked and the preview is displayed

**Acceptance Criteria:**
- Print button should match the existing color scheme
- The button should be centered on the screen
- Button should appear below the preview of results
- Print should display at the same time as the preview section

**Task List:**
- [x] Add print button to the page below filters
- [x] Add styling to match the current color scheme and center
- [x] Toggle the print button to display after the Search button is clicked
