### ISSUE TITLE
Add stored procedure that will accept In Stock, Author, and Genre parameters - 4 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#52]
**Problem:**
As a developer, I need the ability to pull search results based on filters selected in the UI from the database

**Acceptance criteria:**
- create a stored procedure in the database
- stored procedure should accept parameters for In Stock, Author First Name + Last Name, and/or Genre
- information from the stored procedure should be pulled when selecting the Search button on the Available Inventory report screen
- Results will be displayed in a preview screen underneath the search and clear buttons

**Task List:**
- [x] Add stored procedure
- [x] Set stored procedure to accept parameters: In Stock, Author First Name + Last Name, and/or Genre
- [x] run stored procedure when the Search button is clicked
- [x] display results in the preview section on the Available Inventory Report
