### ISSUE TITLE
Create User screens - 3 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#7]
**Problem:**
As a user, I need the ability to have my own account and be able to login.

As a manager, I need the ability to control access that each user account has.

**Acceptance Criteria:**
- A user should be allowed to create their own user account regardless of if they are a guest or an employee.
- A login screen should allow these users to login with the credentials they set up from the create user screen
- An admin screen will be available to control rights for each user as well as change whether they are an employee or guest.

**Task List:**

- [x] Login Screen will be created https://github.com/mbasso29/BestofBooks/milestone/5
- [x] Create User Screen will be created https://github.com/mbasso29/BestofBooks/milestone/6
- [x] Create Admin Screen https://github.com/mbasso29/BestofBooks/milestone/21

**Comment by mbasso29** [comment]
Adding 8 points to this story due to complexity

**Comment by Super-Derek** [comment]
Login Modal has been created. Create User Screen/Form created (non-functional), Admin Screen/Table created (non-functional)
