### ISSUE TITLE
Create a privacy policy screen

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#74]
**Problem:**
As a company, a privacy policy needs to be established to ensure the legal privacy policy is readily available for all users.

**Acceptance Criteria:**
- Generate a privacy policy to cover: created accounts, cookies, device access, personal data, and usage data.
- Add privacy policy to Privacy screen

**Task List**
- [x] Generate privacy policy
- [x] Add privacy policy information to Privacy Screen
- [x] Add styling to Privacy Screen that will match the rest of the website
