### ISSUE TITLE
Create Inventory screen - 4 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#8]
**Problem:**
As a user, I need to be able to view the inventory list and make changes to the entries so that I can keep the database updated to match our current inventory.

**Acceptance Criteria:**
- The inventory list screen needs to be created that will show the company logo and an editable table that books can be added to
- An add option will be added to allow users to add rows
- A delete option will be added per line item to allow the Qty amounts to be set to 0

**Task List:**

- [x] - [x] Create Inventory List screen https://github.com/mbasso29/BestofBooks/milestone/4
- [x] Add button will be added to Inventory List https://github.com/mbasso29/BestofBooks/milestone/7
- [x] Inventory List fields will be editable https://github.com/mbasso29/BestofBooks/milestone/9
- [x] Trash icon will display per line item on Inventory List https://github.com/mbasso29/BestofBooks/milestone/8

**Comment by mbasso29** [comment]
Completed creation of Inventory List screen

**Comment by mbasso29** [comment]
Putting 8 points on this story due to complexity
