### ISSUE TITLE
Add reports screen - 3 points

### ISSUE THREAD

**Issue by mbasso29** [mbasso29/BestofBooks#9]
**Problem:**

As a user, I need the ability to see the list of reports available to view so that I may open, filter and print these reports when necessary.

**Acceptance Criteria:**

- A reports tab will be added that will display a list of reports available to choose
- Each report will be its own link that will open a new page for the report

**Task List:**

- [x] Create Reports Tab https://github.com/mbasso29/BestofBooks/milestone/10
- [x] Add Change History Report Link https://github.com/mbasso29/BestofBooks/issues/33
- [x] Add Inventory List Report Link https://github.com/mbasso29/BestofBooks/issues/34

**Comment by mbasso29** [comment]
Adding 3 points to this story
